name: All GitHub Actions Triggers
run-name: Triggered by @${{ github.actor }} via ${{ github.event_name }}

on:
  ### 1. Ручной запуск (с входными параметрами)
  workflow_dispatch:
    inputs:
      environment:
        description: "Выберите среду"
        required: true
        default: "staging"
        type: choice
        options: [staging, production]
      verbose:
        description: "Включить подробный вывод?"
        required: false
        type: boolean

  ### 2. Push в ветки/теги
  push:
    branches: [main, dev, "feature/*"]
    tags: ["v*.*.*", "!*-beta"]  # Игнорировать теги с -beta

  ### 3. Pull Request
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, closed]
    paths:  # Только если изменены файлы в src/ или .github/
      - "src/**"
      - ".github/workflows/*.yml"

  ### 4. По расписанию (Cron)
  schedule:
    - cron: "0 0 * * *"   # Каждый день в 00:00
    - cron: "0 12 * * 1-5" # В 12:00 по будням

  ### 5. Создание/изменение Issue
  issues:
    types: [opened, edited, labeled]

  ### 6. Комментарии в Issue/PR
  issue_comment:
    types: [created, edited]
    if: contains(github.event.comment.body, '/deploy')

  ### 7. Создание релиза
  release:
    types: [published, prereleased]

  ### 8. Запрос на слияние (Merge Group)
  merge_group:
    branches: [main]

  ### 9. События Wiki
  gollum:  # Изменение Wiki
    branches: [main]

  ### 10. Запуск через API (repository_dispatch)
  repository_dispatch:
    types: [deploy_request]

  ### 11. События проектов (Projects V2)
  project:
    types: [created, edited, closed]

  ### 12. События обсуждений (Discussions)
  discussion:
    types: [answered, created]

  ### 13. События меток (Labels)
  label:
    types: [created, deleted]

jobs:
  detect-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Show trigger info
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Workflow inputs: ${{ toJSON(github.event.inputs) }}"
          echo "Full event data: ${{ toJSON(github.event) }}"
