name: Test GitHub Actions Workflow 2 # Название workflow (отображается в Actions tab)
run-name: ${{ github.actor }} is testing GitHub Actions 🚀  # Динамическое описание запуска

on:
  push:
    branches: [ main, master ]  # Триггер на push в main/master ветку
  pull_request:
    branches: [ main, master ]  # Триггер на PR в main/master ветку
  workflow_dispatch:  # Позволяет запускать workflow вручную из UI

jobs:
  test-job:
    name: Test Job  # Название job внутри workflow
    runs-on: ubuntu-latest  # Запуск на последней Ubuntu

    steps:

      - name: Print a greeting  # Шаг 2: Простое сообщение
        run: echo "Hello, ${{ github.actor }}! GitHub Actions is working! ✅"
