name: Real Permissions Test
on:
  push:

jobs:
  test-repo-read-only:
    permissions: 
      contents: read  # Только чтение (запрет записи)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Try to modify a file (should FAIL)
        run: |
          echo "Test line" >> README.md
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Test commit from Actions" && echo "❌ Unexpected success (should fail!)"
          # Ожидаем ошибку, т.к. нет прав на запись
